package com.example.mybatis4.mapper;

import com.example.mybatis4.entity.TblUser;
import com.example.mybatis4.entity.TblUserExample;
import java.util.List;
import org.springframework.data.repository.query.Param;

public interface TblUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    long countByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int deleteByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int insert(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int insertSelective(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    List<TblUser> selectByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    TblUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblUser record, @Param("example") TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int updateByExample(@Param("record") TblUser record, @Param("example") TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int updateByPrimaryKeySelective(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Wed Jan 15 19:25:59 CST 2020
     */
    int updateByPrimaryKey(TblUser record);
}